name: Deploy to GitHub Releases

permissions:
  contents: write
on:
  push:
    branches:
      - "release"

jobs:
  deploy-to-github-releases:
    runs-on: windows-latest
    env:
      PROJECT_FILE: src/Shell/BrineAndCoin.csproj
      UNIQUE_IDENTIFIER: Brine_and_Coin
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Install Velopack CLI
        run: dotnet tool install -g vpk

      - name: Publish To Windows
        shell: bash
        run: |
          echo "Using project file: $PROJECT_FILE"
          dotnet publish "$PROJECT_FILE" -c Release -o publish-win -r win-x64 --self-contained true
      
      - name: Publish To Linux
        shell: bash
        run: |
          echo "Using project file: $PROJECT_FILE"
          dotnet publish "$PROJECT_FILE" -c Release -o publish-linux -r linux-x64 --self-contained true

      - name: Get Version
        id: get-version
        shell: powershell
        run: |
          $exePath = "publish-win/Portraits_in_Brick_and_Time_-_Brine_And_Coin.exe"
          $version = & $exePath --version
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "version: $version"
          
      - name: Download old release    
        run: |
          vpk download github --repoUrl https://github.com/${{ github.repository }} --token ${{ secrets.GITHUB_TOKEN }}
          vpk [linux] download github --repoUrl https://github.com/${{ github.repository }} --token ${{ secrets.GITHUB_TOKEN }}

      - name: Pack Windows
        run: vpk pack -u "${{ env.UNIQUE_IDENTIFIER }}" -v ${{ steps.get-version.outputs.version }} -p publish-win --mainExe Portraits_in_Brick_and_Time_-_Brine_And_Coin.exe
      
      - name: Pack Linux
        run: vpk [linux] pack -u "${{ env.UNIQUE_IDENTIFIER }}" -v ${{ steps.get-version.outputs.version }} -p publish-linux --mainExe Portraits_in_Brick_and_Time_-_Brine_And_Coin 

      - name: Create Release
        run: |
          vpk upload github --repoUrl https://github.com/${{ github.repository }} --releaseName "${{ steps.get-version.outputs.version }}" --tag v${{ steps.get-version.outputs.version }} --publish --token ${{ secrets.GITHUB_TOKEN }}
          vpk [linux] upload github --merge --repoUrl https://github.com/${{ github.repository }} --releaseName "${{ steps.get-version.outputs.version }}" --tag v${{ steps.get-version.outputs.version }} --publish --token ${{ secrets.GITHUB_TOKEN }}
          